name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to Production
      uses: JorgeLNJunior/render-deploy@v1.4.5
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}
        wait_deploy: true